version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: gardenia_db
      POSTGRES_USER: gardenia
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gardenia -d gardenia_db']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
