export enum CareScheduleActivityTypeEnum {
  WATERING = 'WATERING',
  FERTILIZING = 'FERTILIZING',
  PRUNING = 'PRUNING',
  REPOTTING = 'REPOTTING',
  TRANSPLANTING = 'TRANSPLANTING',
  PEST_TREATMENT = 'PEST_TREATMENT',
  MISTING = 'MISTING',
  ROTATION = 'ROTATION',
  OTHER = 'OTHER',
}
