export enum SensorTypeEnum {
  SOIL_MOISTURE = 'SOIL_MOISTURE',
  SOIL_TEMPERATURE = 'SOIL_TEMPERATURE',
  AMBIENT_TEMPERATURE = 'AMBIENT_TEMPERATURE',
  AMBIENT_HUMIDITY = 'AMBIENT_HUMIDITY',
  LIGHT_LEVEL = 'LIGHT_LEVEL',
  RAIN = 'RAIN',
  WATER_LEVEL = 'WATER_LEVEL',
}
